

# server config
server:
  port: 8002
  
# database config
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url : jdbc:oracle:thin:@localhost:1521:xe
    username:     
    password: 
    
  mail:
    host: smtp.naver.com
    port: 
    username:
    password: 
    properties:
     mail.smtp.auth: true
     mail.smtp.ssl.enable: true    

#file upload config
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      location: D:\workspace\spring\subproject\thunderbolts
  
      
#image upload directory F:/sub_project
image:
  image-dir: src/main/resources/upload/image/  
    
    
    
# mybatis congfig
mybatis:
  mapper-locations: mappers/**/*.xml
  
# log level (root 설정)
logging:
  level:
# root level - 전역 설정
    root: info
#package level - 지역 설정
    '[com.greedy.thunerbolts]': trace 
    
    
 
